let qs=[],i=0,selected=null,used={fifty:false,hint:false,klass:false},scores={A:0,B:0};const $=s=>document.querySelector(s);
async function load(){qs=parse(await fetch('content.txt').then(r=>r.text()));render()}
function parse(t){return t.split(/\n\s*---\s*\n/).map(b=>{let o={};b.split('\n').forEach(l=>{if(!l.trim()||l.trim().startsWith('#'))return;let j=l.indexOf(':');if(j>0)o[l.slice(0,j).trim().toLowerCase()]=l.slice(j+1).trim()});return o}).filter(x=>x.question&&x.a&&x.correct)}
function render(){let q=qs[i%qs.length];selected=null;$('#counter').textContent='Ερώτηση '+(i+1)+' από '+qs.length;$('#question').textContent=q.question;$('#message').textContent='';let a=$('#answers');a.innerHTML=['a','b','c','d'].map((k,n)=>'<button class="answer" data-k="'+k+'"><b>'+'ABCD'[n]+':</b> '+(q[k]||'')+'</button>').join('');a.querySelectorAll('.answer').forEach(b=>b.onclick=()=>{a.querySelectorAll('.answer').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selected=b.dataset.k});renderLadder()}
function renderLadder(){let vals=qs.map(q=>+q.points||100);$('#ladder').innerHTML=vals.map((v,n)=>'<div class="step '+(n===i?'active':'')+'">'+(n+1)+'. '+v+'</div>').join('')}
$('#lock').onclick=()=>{if(!selected)return;let q=qs[i],ok=selected===q.correct.toLowerCase();document.querySelector('[data-k="'+selected+'"]').classList.add(ok?'correct':'wrong');document.querySelector('[data-k="'+q.correct.toLowerCase()+'"]').classList.add('correct');document.querySelectorAll('.answer').forEach(b=>b.disabled=true);let team=$('#team').value;if(ok){let p=+q.points||100;scores[team]+=p;$('#score'+team).textContent=scores[team];$('#message').textContent='Σωστό! +'+p}else $('#message').textContent='Λάθος.'}
$('#next').onclick=()=>{if(i<qs.length-1){i++;render()}else $('#message').textContent='Τέλος παιχνιδιού!'}
$('#fifty').onclick=()=>{if(used.fifty)return;used.fifty=true;let q=qs[i],correct=q.correct.toLowerCase(),wrong=[...'abcd'].filter(k=>k!==correct).slice(0,2);wrong.forEach(k=>document.querySelector('[data-k="'+k+'"]').style.visibility='hidden');$('#fifty').disabled=true}
$('#hintBtn').onclick=()=>{if(used.hint)return;used.hint=true;$('#message').textContent='Υπόδειξη: '+(qs[i].hint||'Δεν υπάρχει υπόδειξη.');$('#hintBtn').disabled=true}
$('#classBtn').onclick=()=>{if(used.klass)return;used.klass=true;$('#message').textContent='Ρώτα την τάξη: ψηφοφορία με ανάταση χεριού για A, B, C ή D.';$('#classBtn').disabled=true};load();